### ISSUE TITLE
History channel versus Viasat History

### ISSUE THREAD

**Issue by Sentinel800** [szabbenjamin/digionline#10]
A History a Viasat history műsorlistáját (kapja meg) update: keveredik a kettő. A következő műsorként már jól a history channel következő műsorát mutatja. Az elnevezés okozna (History-history) bug ot az iptv kliensében?

ui: MTV Europe: javítva

G

**Comment by szabbenjamin** [comment]
Javítva
https://github.com/szabbenjamin/digionline/commit/333a5a44fe53221706a2401cd3594a2049666c91
