### ISSUE TITLE
Servlet leállás internetmegszakadáskor

### ISSUE THREAD

**Issue by ata843** [szabbenjamin/digionline#12]
Üdv! A szervlet internetmegszakadás esetén leáll és újra se tudom indítani, csak ha a kiszolgáló raspberryt teljesen újraindítom (biztos van más megoldás is, de nem vagyok nagy linux admin). Esetleg megoldható lenne, hogy valahogy várakozzon a szervlet az internetkapcsolat helyreállására? Köszönöm!

**Comment by Sentinel800** [comment]
Hello! Nem írtad le, hogy a leírtakat követve jutottál erre, OSMC t használsz-e. Nem tudni, hogy most minden pi indításkor manuálisan indítod el vagy service nek állítottad-e be a servlet-et. Ha linux service nek van beállítva és mondjuk OSMC fut a pi-n, akkor a hiba nem reprodukálható. Kihúztam 1 percre az UTP csatit, visszadugtam és csatornaváltáskor remekül ment tovább.

**Comment by ata843** [comment]
Úgy tűnik vaklárma volt. Sorry. Elsőre nem sikerült beüzemelni a service-t, úgyhogy nodemon-nal próbáltam életben tartani a servletet. Itt lehetett a hiba. Bocsi mégegyszer.
