### ISSUE TITLE
Hibás időzóna

### ISSUE THREAD

**Issue by bela333** [szabbenjamin/digionline#14]
TVheadend esetén (IPTV Simple Clienttel nem próbáltam) a műsorújság eltolódik egy órával. Úgy tűnik, hogy a musor.tv időzónával (GMT) együtt küldi a műsorok idejét. A getHours és a többi függvény ezt átalakítja a jelenlegi időzónára, így a manuális eltolás szükségtelen. Úgy gondolom, hogy hasznosabb illetve pontosabb lenne a kliens felé a +0000 időzónát hirdetni és getHours helyett getUTCHours-ot használni, manuális eltolás nélkül.

**Comment by szabbenjamin** [comment]
Nyári időszámítás során problémás. Korrigáld az eltérést a KODI iptv client epg beállításaiban.
