### ISSUE TITLE
Digi online servlet http https probléma

### ISSUE THREAD

**Issue by akeladroid** [szabbenjamin/digionline#16]
Üdv!

Azt a problémát vettem észre, hogy a digi áttért a https-re, és http-n már nem szolgáltat, a servlet fájlokban meg http kódok vannak csak, bejelentkezés sikeres, listát lekéri, de a tartalom már nem indul el.

Coreelecen használom, de gondolom a többi op. rendszeren sem megy jelenleg.

**Comment by metalanti** [comment]
Gyors fix, ha ez a sor elé beírod
https://github.com/szabbenjamin/digionline/blob/ae643b23e464562014ed7336dbe0655b9dea7356/engine/tv_servlet.js#L20

hogy
```js
response_url = response_url.replace('https', 'http')
```

**Comment by akeladroid** [comment]
Köszönöm, így működik.

**Comment by istvans** [comment]
Én is köszönöm!

**Comment by bgnorg** [comment]
Sziasztok. Sajna nekem erre a sorra csak hibát dob ki. Valaki esetleg elküldené nekem a módosított fájlt? Sajna én csak egy egyszerü User vagyok. Köszönöm.

**Comment by bgnorg** [comment]
Köszi, hálás vagyok.

**Comment by szabbenjamin** [comment]
Nekem már ez a megoldás sem működik. Ahogy nézem a digi refaktorálta a saját webes rendszerét így félig a nulláról kezdve újra meg kell keresnem a lyukakat, hogy használható legyen az app.
Szóval türelem!

**Comment by istvans** [comment]
Nekem ezzel az átmeneti fixszel még mindig rendesen működik. Fura. 😕

**Comment by szabbenjamin** [comment]
Teszek vele még egy próbát, de közben elkezdem csinálni az új verziót, mivel maga a digionline rendszere is megváltozott.

**Comment by szabbenjamin** [comment]
A digi teljesen refaktorálta a rendszerét, de szerencsétlenkedésüknek hála könnyen megfejthető. Egy teljesen új rendszer várható, kicsit más programnyelven, újragondolva és optimalizálva.
Továbbiakról úgy döntöttem nem Facebookon hanem Telegram csoportban fogok hírt adni, csatlakozzatok és a kezdeti (és későbbi hibákról) itt gyorsabban tudunk üzenetet váltani: 
https://t.me/szabbenjamin_digionline

**Comment by szabbenjamin** [comment]
A hiba javításra került a v2-es verzióban.
