### ISSUE TITLE
MTV Europe csatorna streamnek nincs hangja

### ISSUE THREAD

**Issue by Sentinel800** [szabbenjamin/digionline#17]
V2 ben és v1 ben is tesztelve, jelenleg más csatornánál nem jelentkezik, emiatt nem feltétlen az servlet hibája.

**Comment by szabbenjamin** [comment]
A NatGeo-n pedig időnként képhiba van nálam. Próbáltad ideiglenesen átállítani hq-ból más minőségbe?

**Comment by Sentinel800** [comment]
Megnézem másik minőségi beállítással is. Meglátjuk regálnak-e a hibajelentésre. A Nat Geo egyike azon csatornáknak, amiknek free online vételi lehetőségük van, le lehet cserélni a stream elérését arra, ha a jelenség máshol is megvan.

**Comment by Sentinel800** [comment]
National G hiba megerősítve és lejelentve. A MTV Europe hangsáv javítva.

**Comment by Sentinel800** [comment]
Mivel nem sikerült reprodukálniuk, egyenlőre változás nincs-nem lesz, MQ ra rakva a jelenség megszűnik, mintha csak a sávszélességgel\gyenge jellelel lenne a gond és nem bírja - ez persze radikálisan rossz képet ad. 

1-1 hibát a discoverynél is láttam, addig amíg viszont nem állandó jellegű és reprodukálható máshol is a képhiba, nem hiszem, hogy foglalkoznak vele.

A hibát, hisz eredetileg az mtv ről szólt csak, nyugodtan zárhatod.

**Comment by szabbenjamin** [comment]
Azt figyeltem meg, hogy délelőtt általában jó, délután, estefelé jelentkeznek ilyen problémák. A NatGeo pl teljesen megjavult, esténként talán egy órás műsorban 1-2x kockásodik csak egy egy pillanatra a kép.
