### ISSUE TITLE
epg elcsúszás

### ISSUE THREAD

**Issue by 8imo3** [szabbenjamin/digionline#18]
A műsorújság 1 órával előbbre van mint a tényleges műsor. Hosszabb műsoroknál emiatt fel is cseréli a sorrendjüket??
Belenéztem az epg.xml-be már eleve rosszul generálódik.
Probáltam a iptv.simple-be belépitett csúsztatást használni, de semmilyen befolyással nem volt rá.

**Comment by szabbenjamin** [comment]
Azóta tesztelted, illetve használod? A hiba még mindig jelentkezik?
Vedd figyelembe, hogy az óraeltoláshoz némi idő kell, hogy lefrissüljön, esetleg érdemes újraindítani az egész készüléket.

**Comment by istvans** [comment]
Nekem a v1-el +1 ora eltolas kellett, most viszont a v2-vel eltolas nelkul pontos az EPG.

Az EPG ujrairast igy tudod kikenyszeriteni (OSMC-n legalabbis):
```
DB_DIR=$HOME/.kodi/userdata/Database
rm $DB_DIR/Epg*.db $DB_DIR/TV*.db
service mediacenter restart
```

**Comment by szabbenjamin** [comment]
@8imo3 légyszi jelezz vissza, hogy sikerült-e megoldani a problémát!

**Comment by 8imo3** [comment]
Azóta pontos, sima reboot óra állitás látszólag nem volt hatással. 2 napig disable volt az itpv-simple app. Valami beépitett cache lehet a kodiban, vagy nem tudom. Lezárható a hibajegy, bocs a kései válasz miatt.

**Comment by szabbenjamin** [comment]
Köszi a visszajelzést! :)

Nálam is volt egy elcsúszás 1-2 napja, nálam nem időben hanem egy csatornával ment egyel arrébb (ráadásul tvheadend-el!). Ekkor a PVR beállításokban ráböktem az epg adatbázis törlésére, ekkor újra letöltötte a csatornákat és helyreállt minden.
