### ISSUE TITLE
Stream URL ek felülvizsgálata, best url jelenleg a legrosszabb minőségű stream et találja meg

### ISSUE THREAD

**Issue by Sentinel800** [szabbenjamin/digionline#2]
Szia!

A config által kezelt url ek közül jelenleg az első best url opció pont az ellentétes stream et találja meg, azaz a legkisebb felbontásút.

A medium stream rendben teszi a dolgát.

Amikor mindhárom config érték FALSE, akkor első körben a rosszabb minőséggel indít a stream, ami 720p HD csatornákot feljavul kis idő után, de random működik ezzel a beállítással.

**Comment by szabbenjamin** [comment]
A minőség kiválasztására új módszer lesz kivitelezve

**Comment by szabbenjamin** [comment]
Javítva itt: https://github.com/szabbenjamin/digionline/commit/01f69e2201c453f7782cc09822f4df5d1241762e

Felhívom figyelmed, hogy változott a config fájl, a program visszafelé nem kompatibilis a korábbi config.js-el.
https://github.com/szabbenjamin/digionline/blob/v1.0.0/config.sample.js
