### ISSUE TITLE
H!T channel hiba?

### ISSUE THREAD

**Issue by metalanti** [szabbenjamin/digionline#24]
Hello, tegnap vettem észre, h a H!T channel-en be van ragadva egy 2 perces műsor részlet és azt játsza folyamatosan. De közben a digionline felületén meg jó.
Van ötlet, h mi lehet a baj?

**Comment by szabbenjamin** [comment]
Valamilyen szolgáltatói hiba lehetett, nálam nem csinálja. Ha nálad még mindig fennáll a probléma javaslom az app és Kodi újraindítását most, hátha "helyrezökken" :)
