### ISSUE TITLE
digionline servlet hiba

### ISSUE THREAD

**Issue by bgnorg** [szabbenjamin/digionline#25]
Újratelepítettem az OSMC-t egy Raspberry Pi 3 B+-ra és lefuttattam a digionline telepítőjét, ahogy le van írva, de az npm test-nél hibával kidobja.

> Wed Jan 08 2020 08:16:18 GMT+0100 (CET) [ 'Digionline (2.1.2) servlet starting...' ]
Wed Jan 08 2020 08:16:18 GMT+0100 (CET) [ 'Login digionline.hu' ]
/home/osmc/digionline/lib/digionline.js:56
            var token = dom.window.document.querySelector('[name="_token"]').value;
                                                                            ^

TypeError: Cannot read property 'value' of null
    at /home/osmc/digionline/lib/digionline.js:56:77
    at Request._callback (/home/osmc/digionline/lib/common.js:16:17)
    at self.callback (/home/osmc/digionline/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/osmc/digionline/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
npm ERR! Test failed.  See above for more details.

van valami ötlet hogy merre keressem a hibát? A Kodi-ban lévő Digi addon fut rendesen, bár néha eldobálja az adást.

**Comment by szabbenjamin** [comment]
Ebből egyelőre csak annyi látszik, hogy bejelentkezéskor nem találja a program a belépéshez szükséges token-t. Igyekszem ma megnézni és ha van valami visszajelzek!

**Comment by takacsmarton** [comment]
@szabbenjamin : Kis segítség: Én úgy látom, hogy a digi több frontend -et használ, és az egyiknél lejárt az SSL cert. Emiatt nem tudja elkérni a tokent. Tesztből be is állítottam a  digionline.js -ben a request -nél, hogy hagyja figyelmen kívül az SSL hibát, úgy szépen le is generálódott minden.

**Comment by bgnorg** [comment]
Le tudnád írni, hogy ezt hogy csináljam? Csak egy user vagyok. Köszi.

Az Android Outlook<https://aka.ms/ghei36> letöltése

________________________________

**Comment by szabbenjamin** [comment]
SSL figyelmen kívül hagyása erős biztonsági kockázattal jár, így használatát max ideiglenesen javaslom, de semmiképpen sem javasolt tartós megoldásként alkalmazni.
Ha a böngészőben is látható az érvénytelen tanusítvány hibaüzenet akkor érdemes lenne felvenni a kapcsolatot a Digivel, hogy hozzák már rendbe.

**Comment by takacsmarton** [comment]
@szabbenjamin Igen, természetesen ideiglenesen marad az SSL figyelmen kívül hagyása, a hiba böngészőben is előidézhető. Írtam az ügyfélszolgálatnak emailt, de nem vagyok benne biztos, hogy hamar fognak reagálni.

**Comment by szabbenjamin** [comment]
@takacsmarton azt esetleg elárulnád, hogy melyik országrészben laksz, ahol ezt a hibát tapasztalod? Én itt Miskolcon még egyszer sem kaptam ilyen hibát eddig.

**Comment by bgnorg** [comment]
Én Németországban használom és a böngészőből nyitva "nem biztonságos oldal"-ként azonosítja a digionline.hu-t.

**Comment by takacsmarton** [comment]
@szabbenjamin Pest megyében. A supportnak több felületen is írtam, az egyiken azt mondták, hogy dolgoznak rajta, a másikon még egy kis ping-pong van, mert nem teljesen értették a lényeget.

**Comment by bgnorg** [comment]
> @szabbenjamin : Kis segítség: Én úgy látom, hogy a digi valszeg loadbalancer -t használ, ezért nem mindig ugyan az szolgál ki, és az egyiknél lejárt az SSL cert. Emiatt nem tudja elkérni a tokent. Tesztből be is állítottam a digionline.js -ben a request -nél, hogy hagyja figyelmen kívül az SSL hibát, úgy szépen le is generálódott minden.

Le tudnád írni hogy ezt miként csináljam? Tegnap 3x hívtam az ügyfélszolgálatot, de még mindíg dolgoznak a hibán. Ha nem publikus, akkor légyszives a bgnorg kukac outlook de -re küld el. Köszönöm előre is.

**Comment by szabbenjamin** [comment]
A napokban kiadok egy patch-et ahol kikapcsolható lesz a cert ellenőrzése. Úgy látszik elég sok usert érint a probléma.

**Comment by szabbenjamin** [comment]
Patch fenn van.

Frissítés menete: 
`git pull origin master`
_config.ts módosítása a config.sample.ts fájl alapján_
**A "secureConnection"-t false-ra kell állítani!**
`npm test`
Ha sikeres a belépés és nem lép ki hibával örül!

Várom a visszajelzéseket!

**Comment by 8imo3** [comment]
> Patch fenn van.
> 
> Frissítés menete:
> `git pull origin master`
> _config.ts módosítása a config.sample.ts fájl alapján_
> **A "secureConnection"-t false-ra kell állítani!**
> `npm test`
> Ha sikeres a belépés és nem lép ki hibával örül!
> 
> Várom a visszajelzéseket!

Nálam is ez volt a gond, remélem a digi mielőbb cseréli a lejárt certet.

**Comment by szabbenjamin** [comment]
Akkor lezárom a jegyet. Köszönöm az együttműködést! 🙌
