### ISSUE TITLE
Cannot find module 'D:\digionline\main.js'

### ISSUE THREAD

**Issue by graflandras** [szabbenjamin/digionline#28]
Szia!
Windowson git clone és npm install után npm start-ra az issue cimben lévő hibát dob. Ez mondjuk érthető, mert a packagejson alapján main.js-t keres, de csak ts van. 
node main.ts indítással próbálkozva pedig ezt a hibát kapom: 
$ node main.ts
D:\digionline\main.ts:1
import Webconnect from "./lib/webconnect";
^^^^^^

SyntaxError: Cannot use import statement outside a module

Én csinálok valamit rosszul? Köszönöm!

**Comment by szabbenjamin** [comment]
Előtte futtattál npm test-et?

Mobilról küldve

graflandras <notifications@github.com> ezt írta (időpont: 2020. ápr. 26., V
18:50):

**Comment by graflandras** [comment]
Nálam volt a hiba, a typescript globális telepítése után ($ npm install -g typescript) működik. Köszönöm!
