### ISSUE TITLE
EPG fájl üres

### ISSUE THREAD

**Issue by Merwenus** [szabbenjamin/digionline#29]
Napok óta nincs műsorújság, úgyhogy frissítettem, újraindítottam, lejátszás működik, de az EPG.XML fálban csak ennyi szerepel:
`<?xml version="1.0" encoding="utf-8" ?><tv></tv>`

Amit próbáltam
1) Töröltem az EPG fájlt
2) Újraindítottam a rendszert
3) Újratelepítettem a servletet

`NPM TEST` paranccsal szépen lefut, mintha generálná a műsorújságot, mutat mindent, de a végeredmény sajnos egy majdnem teljesen üres fál.

**Comment by bgnorg** [comment]
Üdv mindenkinek. Nekem ugyanez a probléma. A másik érdekesség,hogy akár frissítem,vagy teljesen újratelepítem, az npm test-nél 2.1.4 verziót ír ki. A servlet maga fut hiba nélkül. Coreelec 9.2.2

**Comment by Merwenus** [comment]
Átmenetileg ezt a megoldást használd:
https://logout.hu/tema/kodi_xbmc_kiegeszito_magyar_nyelvu_online_filmekhe/hsz_29767-29767.html

**Comment by bgnorg** [comment]
Köszi,így legalább epg van. De ezt a frissítéses rész még érdekes. Vagy lehet hogy csak a verziószám nem változott a programban.

**Comment by Merwenus** [comment]
Nem hiszem, nálam nincs auto update, így az nem okozhatta.

**Comment by szabbenjamin** [comment]
Javítás fenn van, az üres xml fájlt az okozta, hogy a korábbi csatorna id-k megszüntek, a múltkor fixáltam, hogy tvheadend-en működjenek a dolgok, akkor nem jutott eszembe, hogy ez az epg-re is kihatással lehet.

Telepítés:
git pull origin master
rm epg.timestamp
npm test

Várd meg míg legenerálja az xml-t, csekkold le, hogy fel is tudja-e olvasni a lejátszóprogramod. Ha továbbra is valami gond lenne szóljatok nyugodtan.
