### ISSUE TITLE
Qnap - Docker problem

### ISSUE THREAD

**Issue by pinceajto** [szabbenjamin/digionline#30]
Sziasztok!

Segítségeteket szeretném kérni.
Qnap Container Station-ben szeretném futtattni docker-ként a progit, azonban sajnos valamiért a bejelentkezés mindig Falat error-t dob. Próbáltam több helyen a config.ts file-t megadni az adatokkal, de nem akar bejelentkezni.

Van valakinek ötlete vagy tapasztalata a dologgal kapcsolatban?

Előre is köszi.

**Comment by szabbenjamin** [comment]
Szia!
Tudnál mutatni egy konzol logot? Ha most update-elsz nem oldódik meg a probléma?
