### ISSUE TITLE
Docker paraméterek

### ISSUE THREAD

**Issue by kbalint** [szabbenjamin/digionline#31]
Helló, nagyon jó a cucc, köszi! 
PI3+-ra raktam docker containerben, simán felment gond nélkül. Annyi, hogy lehet a config.server.address / port-ot ki lehetne emelni paraméterbe még, mert nálam pl. mediaserver.lan lett, és ezt bele kellett vi-znem a config.js-be, de hát soha rosszabbat :)
Sony Android TV-n Kodi IPTV pluginnel tökéletesen működik!

**Comment by szabbenjamin** [comment]
Szia!
Ha beküldesz ezzel egy pull request-et akkor megnézzük és jóváhagyom. Dockerben sajnos nem vagyok járatos, a fenn lévő dockerfile-t is egy felhasználó pusholta fel 🙄 😁
