### ISSUE TITLE
epg.xml: Hunting & Fishing

### ISSUE THREAD

**Issue by kbalint** [szabbenjamin/digionline#42]
Nem tudom más tapasztalta-e, de nálam Kodi 18.8 alatt nem megy a műsorújság, mivel nem valid a generált XML:  
`<channel id="id303"><display-name lang="hu">The Fishing & Hunting</display-name></channel>`
szerintem a csatornanevekben is ki kellene escape-elni a speciális karaktereket.

**Comment by droM4X** [comment]
Ilyen hibak elofordulhatnak. OSMC az ajanlott setup, ott pedig a legfrissebb kiadas (2020.06) a 18.7-es Kodit hasznalja, ahol nincs problema ebbol (nalam legalabbis jol megy az epg, es a fishing & huntingnal is jol mutatja)

Aki mas setuppal hasznalja, ott lehetnek problema, persze ettol fuggetlenul lehetne/kene fixelni.
Mar musor cimben is lattam hibas megjelenest valoszinuleg egy ' vagy " miatt, kell ra fix.
A heten ranezek, ha addig nem patkolja meg valaki.

**Comment by kbalint** [comment]
https://github.com/szabbenjamin/digionline/pull/43 tessék

**Comment by szabbenjamin** [comment]
Egyelőre ahogy nézem más karaktereket nem érint a probléma, de elképzelhető, hogy később fog, majd odafigyelek, vagy kitalálok mást az escape-elésre. Egyelőre ezt a pull request-et beengedtem, aztán letesztelem hogy reagál rá az OSMC-m.
