### ISSUE TITLE
win 10 

### ISSUE THREAD

**Issue by csabaturul** [szabbenjamin/digionline#45]
sziasztok.. hogy tudom megoldani hogy a digionline fusson win 10 en???

**Comment by aburamses** [comment]
Megnyitod böngészőben felhasználó névvel és jelszóval bejelentkezve?

**Comment by csabaturul** [comment]
kodin keresztül akarom nézni

**Comment by aburamses** [comment]
Akkor miért kell win10? Bocs, de nem értem...

**Comment by csabaturul** [comment]
az a gondom hogy egyik digi online alkalmazas sem hd ban van

**Comment by csabaturul** [comment]
alkalmazás

**Comment by csabaturul** [comment]
arra gondoltam hogy a m3u fáljt amit kapok a bejelentkezes utan azt használnám  vlc  esetleg enigma2 stb hez

**Comment by aburamses** [comment]
Gondolod így működik a HD-tartalom?

**Comment by NH3CL** [comment]
Szerintem ennek fuss neki még egyszer. Mármint annak, hogy leírod mit szeretnél.

Ez a plugin OSMC-hez van elsősorban, az pedig linuxon fut. A plugin korántsem csak annyit csinál, hogy letölti neked a csatornalistát...
