### ISSUE TITLE
Digi online m3u

### ISSUE THREAD

**Issue by joco80** [szabbenjamin/digionline#49]
Hello 
Érdeklődnék kezdő vagyok van digi online hozzá férésem elofizetesem stb 
Nem értem hogy hogyan tudnám megszerezni a saját M3u csatorna listámat 
Mac gépem van azon hogyan tudnám megszerezni ? Vagy egyáltalán hol találom ezt az m3u saját listamat 
Előre is köszönöm a segítséget

**Comment by droM4X** [comment]
Ott van a leirasban:

> E program indításakor legenerál egy m3u és egy xml fájlt - az előbbiben a teljes csatornalista az utóbbiban 5 napra előre elektronikus programujság (EPG) található, melyet képes lejátszani a VLC, de teljes műsorújsággal együtt a KODI is. Mielőtt megkérdeznéd, igen, kell ennek az alkalmazásnak folyamatosan futnia amikor tévézel és nem, nem elég az m3u és az xml fájlt "csak valahova átmásolni".

**Comment by droM4X** [comment]
Mukodik macen is (legalabbis nekem regebben ment), csak ez a verzio rasperry pi 2/3 omsc-re keszult, a telepito scriptet kicsit at kell irni hogy fel tudd telepiteni.
Dockerben is fel tudod tenni, vagy van [Ubuntura leiras](https://github.com/szabbenjamin/digionline/wiki/Telep%C3%ADt%C3%A9s-Ubuntu-18.04-rendszerre) illetve az en [debian only forkom](https://github.com/droM4X/digionline) ahol megadhato hova telepitse (raspberry pi 4-re keszult, mert oda nincs omsc vagy barmilyen debian alapu rendszerre).
