### ISSUE TITLE
Nem elérhetö csatornák

### ISSUE THREAD

**Issue by Zoli1972** [szabbenjamin/digionline#51]
Helló szabbenjamin,

A Digi nemrég változtatott a csatorna-kiosztáson (pl. RTL Spike / Paramount Network / Paramount Channel / Cool TV).
Legalább a Paramount és a Cool ez által elérhetetlenné váltak, de lehet hogy még további adó is.

Ehhez kapcsolódóan tudnád frissíteni az m3u8 file-t?

Üdv
Zoli

**Comment by szabbenjamin** [comment]
Szia!

Az m3u8 fájlnak automatikusan újra kellene generálódnia a változtatást követően, mert indításkor tölti le a program az aktuális csatornalistát. Tehát elvileg nem lenne akadálya, hogy amit írsz automata megtörténjen. 

Viszont az EPG-t kézileg kell frissítenem, köszi, hogy szóltál!

**Comment by szabbenjamin** [comment]
EPG frissítve. 
Ha még mindig vannak lejátszási problémák nyisd újra a jegyet!
