### ISSUE TITLE
Kodi 19 help

### ISSUE THREAD

**Issue by kbalint** [szabbenjamin/digionline#56]
Helló, eddig minden ment rendben, de a tévén a kodi upgrade-elte magát, és bár a tv channelek és a kategóriáik is remekül megjelennek (ez van az xml-ben, ugye?) a tévé adást már nem tudja lejátszani valami miatt.
2 addon van telepítve, a PVR IPTV simple client (7.5.1.) és a Tvheadend HTSP Client (8.3.0). A kodi log szerint ez utóbbi glitchel, azt mondja h "server is unreachable", míg közben a docker konténerben ez történik:

```
Thu May 06 2021 12:45:22 GMT+0000 (Coordinated Universal Time) [ 'Server is listening' ]
Thu May 06 2021 12:45:22 GMT+0000 (Coordinated Universal Time) [ 'Generating channel list...', '.m3u8' ]
Thu May 06 2021 12:45:22 GMT+0000 (Coordinated Universal Time) [ 'Channel list ready.' ]
Thu May 06 2021 12:45:22 GMT+0000 (Coordinated Universal Time) [ 'EPG naprakesz' ]
Thu May 06 2021 12:45:33 GMT+0000 (Coordinated Universal Time) [ 'GET channel 0' ]
Thu May 06 2021 12:45:33 GMT+0000 (Coordinated Universal Time) [ '################# FATAL ERROR #############' ]
Thu May 06 2021 12:45:33 GMT+0000 (Coordinated Universal Time) [ 'Channel id is not found.' ]
Thu May 06 2021 12:45:33 GMT+0000 (Coordinated Universal Time) [ 'loaded from request', 'id_0' ]

> digionline@2.2.1 start /usr/src/app
> node main.js

Thu May 06 2021 12:45:43 GMT+0000 (Coordinated Universal Time) [ 'Digionline (2.2.1) servlet starting...' ]
```

hogy tudom ezt a kócerájt újra működőképessé tenni vajon? Köszi előre is

**Comment by szabbenjamin** [comment]
Hali!

A hibát biztosan nem a 19-es Kodi, sem iptv plugin, sem a tvheadend okozza. A "GET channel 0" a logban azt jelzi, hogy a digi rendszeréből nem tudott egyetlen csatornát sem letölteni a program. Ez lehet a digionline szerverhibája is, de lehet az is, hogy neked is hibás SSL-t generált, bár azt a hibát a rendszer máshogyan kellene jeleznie.

Biztosan jó a digionline accountod? Böngészőben megnyitva számítógépen tudsz megnyitni tv csatornákat? Én most átnéztem a jelenleg aktív rendszert, nekem úgy tűnik nem változott semmi, tehát nálad is működnie kellene a lejátszásnak.

Végső esetben próbáld meg újratelepíteni a dockerbe telepített digionline alkalmazást.

**Comment by kbalint** [comment]
Szia, kösz a választ! Hát már mindent próbáltam, újrahúztam a konténert, beleírtam a js-be a "tvg-chno"-t, hátha azt hiányolja,  aztán a végén felraktam a tivimate appot, és azzal meg csont nélkül működik a tv-n a konténerből, úgyhogy a kodi ment is a levesbe... btw win10/linux desktopon vlc-vel a kezdetektől kifogástalan minden. UFÓ
