### ISSUE TITLE
Raspberry 4 telepítés 

### ISSUE THREAD

**Issue by bobbyjackson1** [szabbenjamin/digionline#57]
Sziasztok,

Raspi 4-en mi lenne a legideálisabb megoldás arra, hogy LG webos-es TV működjön az app? Az ideális az lenne, hogy webos-es appból lehetne elérni a csatornákat.
Korábban már használtam Plexet nem tűnik rossz alkalmazásnak viszont, ahogy néztem itt már kivették a plugineket amivel meglehetett volna oldani fájlok betöltését.

Egyébként köszi, király cuccot csináltatok.

**Comment by szabbenjamin** [comment]
WebOS-en (az LG smart TV-s saját oprendszerén) elvileg a Smart IPTV program meg tudja nyitni a digionline app csatornáit. Nekem még nem sikerült érdemben ezzel dűlőre jutni, pedig nekem is LG tévém van.
Egy esetleges - bár nem túl elegáns megoldás - ha a raspi4-esre telepítesz egy GUI-val rendelkező Raspberry Pi OS-t és arra egy KODI-t, plusz ezt az appot akkor a raspi lenne a kvázi beltéri egységed, ami megnyitja a digionline appot és a KODI-t is. 

BTW annyira figyelj oda, hogy ne 4K legyen a raspi kimenete - úgy a KODI nem fog valami jól produkálni. Mivel egyik csatorna se ténylegesen fullHD így simán elég 720p-t belőni.

Vagy a másik...egy olyan raspi-t szerezni, amire telepíthető OSMC. Elég érthetetlen, hogy még azóta sem adtak ki OSMC-t raspi4-re...

**Comment by NH3CL** [comment]
> 
> 
> Sziasztok,
> 
> Raspi 4-en mi lenne a legideálisabb megoldás arra, hogy LG webos-es TV működjön az app? Az ideális az lenne, hogy webos-es appból lehetne elérni a csatornákat.
> Korábban már használtam Plexet nem tűnik rossz alkalmazásnak viszont, ahogy néztem itt már kivették a plugineket amivel meglehetett volna oldani fájlok betöltését.
> 
> Egyébként köszi, király cuccot csináltatok.

Felrakod Pi 4-re az OSMC-t, utána pedig:
https://github.com/szabbenjamin/digionline/releases/tag/v2.2.9
