### ISSUE TITLE
Üres epg.xml

### ISSUE THREAD

**Issue by NH3CL** [szabbenjamin/digionline#58]
Sziasztok,

Tegnap elszállt a műsorújság, üres az epg.xml

> 2021-07-20 09:09:46.778 T:1141891296   ERROR: AddOnLog: PVR IPTV Simple Client: Unable to load EPG file '/home/osmc/digionline/epg.xml':  file is missing or empty. :1th try.
> 2021-07-20 09:09:48.779 T:1141891296   ERROR: AddOnLog: PVR IPTV Simple Client: Unable to load EPG file '/home/osmc/digionline/epg.xml':  file is missing or empty. :2th try.
> 2021-07-20 09:09:49.957 T:1709166816 WARNING: CPythonInvoker(17, /home/osmc/.kodi/addons/script.extendedinfo/plugin.py): the python script "/home/osmc/.kodi/addons/script.extendedinfo/plugin.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui10DialogBusyE
> 2021-07-20 09:09:50.781 T:1141891296   ERROR: AddOnLog: PVR IPTV Simple Client: Unable to load EPG file '/home/osmc/digionline/epg.xml':  file is missing or empty. :3th try.
> 2021-07-20 09:09:50.782 T:1141891296   ERROR: AddOnLog: PVR IPTV Simple Client: Unable to load EPG file '/home/osmc/digionline/epg.xml':  file is missing or empty. After 3 tries.
> 2021-07-20 09:09:55.048 T:1181737184 WARNING: CPythonInvoker(18, /home/osmc/.kodi/addons/script.extendedinfo/plugin.py): the python script "/home/osmc/.kodi/addons/script.extendedinfo/plugin.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui10DialogBusyE
> 2021-07-20 09:09:56.789 T:1656725728 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
> 2021-07-20 09:09:56.789 T:1656725728  NOTICE: LoadJpeg: unable to load special://skin/backgrounds/default_bg.jpg
> ^C
> osmc@NHTV:~/.kodi$ cat /home/osmc/digionline/epg.xml
> osmc@NHTV:~/.kodi$ cd ..
> osmc@NHTV:~$ cd digionline/
> osmc@NHTV:~/digionline$ ./force_epg_reload.sh
> TV adatbazis torles... kesz
> kodi ujrainditas... kesz
> varunk 10 masodpercet... kesz
> a friss adatbazis ellenorzese
> -rw-r--r-- 1 osmc osmc 28K Jul 20 09:10 /home/osmc/.kodi/userdata/Database/Epg12.db
> -rw-r--r-- 1 osmc osmc 40K Jul 20 09:10 /home/osmc/.kodi/userdata/Database/TV32.db
> osmc@NHTV:~/digionline$ cat /home/osmc/digionline/epg.xml
> osmc@NHTV:~/digionline$
> 

reload után is üres marad.

**Comment by szabbenjamin** [comment]
Hali!

Ha leállítod a digionline service-t (systemctl stop digionline) és kézzel indítod el a mappájában (npm start) mit kapsz a kimeneten?

**Comment by NH3CL** [comment]
> root@NHTV:/home/osmc/digionline# npm start
npm WARN npm npm does not support Node.js v10.24.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> digionline@2.2.6 start /home/osmc/digionline
> node main.js

/home/osmc/digionline/lib/config.js:14
                throw new Error('config.json hiba! ' + e);
                ^

Error: config.json hiba! Error: ENOENT: no such file or directory, open 'config.json'
    at Function.Config.instance (/home/osmc/digionline/lib/config.js:14:23)
    at Object.<anonymous> (/home/osmc/digionline/lib/common.js:9:32)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/osmc/digionline/lib/webconnect.js:6:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! digionline@2.2.6 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the digionline@2.2.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-20T07_50_10_835Z-debug.log


> root@NHTV:/home/osmc/digionline# cat /root/.npm/_logs/2021-07-20T07_50_10_835Z-debug.log
0 info it worked if it ends with ok
1 warn npm npm does not support Node.js v10.24.0
2 warn npm You should probably upgrade to a newer version of node as we
3 warn npm can't make any promises that npm will work with this version.
4 warn npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
5 warn npm You can find the latest version at https://nodejs.org/
6 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
7 info using npm@5.8.0
8 info using node@v10.24.0
9 verbose run-script [ 'prestart', 'start', 'poststart' ]
10 info lifecycle digionline@2.2.6~prestart: digionline@2.2.6
11 info lifecycle digionline@2.2.6~start: digionline@2.2.6
12 verbose lifecycle digionline@2.2.6~start: unsafe-perm in lifecycle true
13 verbose lifecycle digionline@2.2.6~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/osmc/digionline/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/osmc/bin:/opt/vc/bin
14 verbose lifecycle digionline@2.2.6~start: CWD: /home/osmc/digionline
15 silly lifecycle digionline@2.2.6~start: Args: [ '-c', 'node main.js' ]
16 silly lifecycle digionline@2.2.6~start: Returned: code: 1  signal: null
17 info lifecycle digionline@2.2.6~start: Failed to exec start script
18 verbose stack Error: digionline@2.2.6 start: `node main.js`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:283:16)
18 verbose stack     at EventEmitter.emit (events.js:198:13)
18 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:198:13)
18 verbose stack     at maybeClose (internal/child_process.js:982:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
19 verbose pkgid digionline@2.2.6
20 verbose cwd /home/osmc/digionline
21 verbose Linux 4.19.122-2-osmc
22 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
23 verbose node v10.24.0
24 verbose npm  v5.8.0
25 error code ELIFECYCLE
26 error errno 1
27 error digionline@2.2.6 start: `node main.js`
27 error Exit status 1
28 error Failed at the digionline@2.2.6 start script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]

**Comment by NH3CL** [comment]
Sikerült addig faragnom, hogy már el se indul :D

> 2021-07-20 10:02:25.103 T:1915827120  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/Minden csatorna/pvr.iptvsimple_683460943.pvr
2021-07-20 10:02:25.104 T:1116414176  NOTICE: Creating InputStream
2021-07-20 10:02:25.106 T:1116414176   ERROR: CCurlFile::FillBuffer - Failed: Couldn't connect to server(7)
2021-07-20 10:02:25.106 T:1116414176   ERROR: CCurlFile::Open failed with code 0 for http://localhost:9999/channel/267.m3u8:
2021-07-20 10:02:25.106 T:1116414176  NOTICE: Creating Demuxer
2021-07-20 10:02:25.108 T:1116414176   ERROR: OpenDemuxStream - Error creating demuxer
2021-07-20 10:02:25.108 T:1116414176  NOTICE: CVideoPlayer::OnExit()
2021-07-20 10:02:25.210 T:1915827120  NOTICE: CVideoPlayer::CloseFile()
2021-07-20 10:02:25.210 T:1915827120  NOTICE: VideoPlayer: waiting for threads to exit
2021-07-20 10:02:25.211 T:1915827120  NOTICE: VideoPlayer: finished waiting
2021-07-20 10:02:25.284 T:1589580000   ERROR: EXCEPTION: XBMC is not playing any file
2021-07-20 10:02:25.286 T:1589580000   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: XBMC is not playing any file
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/service.autosubs/default.py", line 114, in onPlayBackStarted
                                                movieFullPath = xbmc.Player().getPlayingFile()
                                            RuntimeError: XBMC is not playing any file
                                            -->End of Python script error report<--

**Comment by szabbenjamin** [comment]
Gondolom frissítettél. 
Howto: https://github.com/szabbenjamin/digionline/releases/tag/v2.2.8

**Comment by NH3CL** [comment]
> ^Croot@NHTV:/home/osmc/digionline# npm test
npm WARN npm npm does not support Node.js v10.24.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> digionline@2.2.6 test /home/osmc/digionline
> tsc main.ts && node main.js

Tue Jul 20 2021 10:44:17 GMT+0200 (Central European Summer Time) [ 'Digionline (2.2.6) servlet starting...' ]
Tue Jul 20 2021 10:44:18 GMT+0200 (Central European Summer Time) [ 'Login digionline.hu' ]
Tue Jul 20 2021 10:44:18 GMT+0200 (Central European Summer Time) [ '7 napnal regebbi logfajlok torlese...' ]
Tue Jul 20 2021 10:44:24 GMT+0200 (Central European Summer Time) [ 'Logged in: neutrino' ]
@
@
@
@
@ Ha támogatni szeretnéd a munkámat (vagy meg szeretnél hívni egy sörre, kávéra) Paypal-on van erre lehetőséged: https://paypal.me/dicsportal
@
@
@
Tue Jul 20 2021 10:44:24 GMT+0200 (Central European Summer Time) [ 'Loading channel list...' ]
Tue Jul 20 2021 10:44:27 GMT+0200 (Central European Summer Time) [ 'Fetching channel categories...' ]
Tue Jul 20 2021 10:44:28 GMT+0200 (Central European Summer Time) [ 'Channels loaded', 55 ]
Tue Jul 20 2021 10:44:28 GMT+0200 (Central European Summer Time) [ '===Elerheto csatornalista formatumok kulso lejatszokhoz===' ]
Tue Jul 20 2021 10:44:28 GMT+0200 (Central European Summer Time) [ 'http://localhost:9999/channels_IPTV.m3u8' ]
Tue Jul 20 2021 10:44:28 GMT+0200 (Central European Summer Time) [ 'http://localhost:9999/channels_tvheadend.m3u8' ]
Tue Jul 20 2021 10:44:28 GMT+0200 (Central European Summer Time) [ 'http://localhost:9999/epg.xml' ]
Tue Jul 20 2021 10:44:28 GMT+0200 (Central European Summer Time) [ 'http://localhost:9999/channels.csv' ]
Tue Jul 20 2021 10:44:28 GMT+0200 (Central European Summer Time) [ 'Server is listening' ]
Tue Jul 20 2021 10:44:28 GMT+0200 (Central European Summer Time) [ 'Generating channel list...', '.m3u8' ]
Tue Jul 20 2021 10:44:28 GMT+0200 (Central European Summer Time) [ 'Channel list ready.' ]
Tue Jul 20 2021 10:44:28 GMT+0200 (Central European Summer Time) [ 'EPG lista típusa: heti' ]
Tue Jul 20 2021 10:44:28 GMT+0200 (Central European Summer Time) [ 'EPG naprakesz' ]


Itt áll meg a dolog

**Comment by szabbenjamin** [comment]
config.json-ben az epg forceUpdate -et billentsd true-ra légyszi

**Comment by NH3CL** [comment]
Most itt áll meg:

> Tue Jul 20 2021 10:55:33 GMT+0200 (Central European Summer Time) [ 'Loading channel list...' ]
Tue Jul 20 2021 10:55:37 GMT+0200 (Central European Summer Time) [ 'Fetching channel categories...' ]
Tue Jul 20 2021 10:55:38 GMT+0200 (Central European Summer Time) [ 'Channels loaded', 55 ]
Tue Jul 20 2021 10:55:38 GMT+0200 (Central European Summer Time) [ '===Elerheto csatornalista formatumok kulso lejatszokhoz===' ]
Tue Jul 20 2021 10:55:38 GMT+0200 (Central European Summer Time) [ 'http://localhost:9999/channels_IPTV.m3u8' ]
Tue Jul 20 2021 10:55:38 GMT+0200 (Central European Summer Time) [ 'http://localhost:9999/channels_tvheadend.m3u8' ]
Tue Jul 20 2021 10:55:38 GMT+0200 (Central European Summer Time) [ 'http://localhost:9999/epg.xml' ]
Tue Jul 20 2021 10:55:38 GMT+0200 (Central European Summer Time) [ 'http://localhost:9999/channels.csv' ]
Tue Jul 20 2021 10:55:38 GMT+0200 (Central European Summer Time) [ 'Server is listening' ]
Tue Jul 20 2021 10:55:38 GMT+0200 (Central European Summer Time) [ 'Generating channel list...', '.m3u8' ]
Tue Jul 20 2021 10:55:38 GMT+0200 (Central European Summer Time) [ 'Channel list ready.' ]
Tue Jul 20 2021 10:55:38 GMT+0200 (Central European Summer Time) [ 'EPG lista típusa: heti' ]
Tue Jul 20 2021 10:55:38 GMT+0200 (Central European Summer Time) [ 'EPG kenyszeritett ujratoltese...' ]
Tue Jul 20 2021 10:55:42 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: VIASAT3...' ]
Tue Jul 20 2021 10:55:51 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: TV2 Séf...' ]
Tue Jul 20 2021 10:56:00 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: TeenNick...' ]
Tue Jul 20 2021 10:56:11 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: SONY MAX...' ]
Tue Jul 20 2021 10:56:17 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: Paramount Network...' ]
Tue Jul 20 2021 10:56:21 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: Nick Jr....' ]
Tue Jul 20 2021 10:56:34 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: FILM4...' ]
Tue Jul 20 2021 10:56:38 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: Film Café...' ]
Tue Jul 20 2021 10:56:42 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: CBS Reality...' ]
Tue Jul 20 2021 10:56:49 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: AXN...' ]
Tue Jul 20 2021 10:56:53 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: Film Now...' ]
Tue Jul 20 2021 10:56:58 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: SuperTV2...' ]
Tue Jul 20 2021 10:57:03 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: TV2 Comedy...' ]
Tue Jul 20 2021 10:57:09 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: TV2...' ]
Tue Jul 20 2021 10:57:15 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: PRIME...' ]
Tue Jul 20 2021 10:57:21 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: Izaura...' ]
Tue Jul 20 2021 10:57:27 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: TLC...' ]
Tue Jul 20 2021 10:57:33 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: FEM3...' ]
Tue Jul 20 2021 10:57:39 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: Nickelodeon...' ]
Tue Jul 20 2021 10:57:48 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: Minimax...' ]
Tue Jul 20 2021 10:57:56 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: TV2 Kids...' ]
Tue Jul 20 2021 10:58:05 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: JimJam...' ]
Tue Jul 20 2021 10:58:15 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: Zenebutik...' ]
Tue Jul 20 2021 10:58:20 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: Sláger TV...' ]
Tue Jul 20 2021 10:58:24 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: Music Channel...' ]
Tue Jul 20 2021 10:58:28 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: MTV Hungary...' ]
Tue Jul 20 2021 10:58:32 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: H!T Music Channel...' ]
Tue Jul 20 2021 10:58:36 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: TV Paprika...' ]
Tue Jul 20 2021 10:58:41 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: Viasat Nature...' ]
Tue Jul 20 2021 10:58:45 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: Viasat History...' ]
Tue Jul 20 2021 10:58:49 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: HISTORY...' ]
Tue Jul 20 2021 10:58:53 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: DIGI Life...' ]
Tue Jul 20 2021 10:58:57 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: DIGI World...' ]
Tue Jul 20 2021 10:59:01 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: DIGI Animal World...' ]
Tue Jul 20 2021 10:59:05 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: Nat Geo WILD...' ]
Tue Jul 20 2021 10:59:09 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: Nat Geo...' ]
Tue Jul 20 2021 10:59:13 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: Discovery Channel...' ]
Tue Jul 20 2021 10:59:17 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: Spektrum...' ]
Tue Jul 20 2021 10:59:21 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: The Fishing & Hunting...' ]
Tue Jul 20 2021 10:59:26 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: DIGI Sport 3...' ]
Tue Jul 20 2021 10:59:30 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: DIGI Sport 2...' ]
Tue Jul 20 2021 10:59:34 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: DIGI Sport 1...' ]
Tue Jul 20 2021 10:59:38 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: Eurosport 2...' ]
Tue Jul 20 2021 10:59:42 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: Eurosport...' ]
Tue Jul 20 2021 10:59:46 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: SPORT2...' ]
Tue Jul 20 2021 10:59:50 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: SPORT1...' ]
Tue Jul 20 2021 10:59:54 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: M4 Sport...' ]
Tue Jul 20 2021 10:59:58 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: Mozi+...' ]
Tue Jul 20 2021 11:00:02 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: Comedy Central...' ]
Tue Jul 20 2021 11:00:07 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: AMC...' ]
Tue Jul 20 2021 11:00:11 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: M5...' ]
Tue Jul 20 2021 11:00:16 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: Duna World...' ]
Tue Jul 20 2021 11:00:21 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: Duna...' ]
Tue Jul 20 2021 11:00:25 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: M2...' ]
Tue Jul 20 2021 11:00:33 GMT+0200 (Central European Summer Time) [ 'EPG betoltese: M1...' ]
Tue Jul 20 2021 11:00:39 GMT+0200 (Central European Summer Time) [ 'epg.xml ujrairva' ]

**Comment by szabbenjamin** [comment]
és az EPG xml ezek után is üres?

**Comment by NH3CL** [comment]
Nem, már van tartalma, viszont a Simple IPTV nem tölti be.

**Comment by szabbenjamin** [comment]
> Nem, már van tartalma, viszont a Simple IPTV nem tölti be.
Vele próbálkoztál már? https://github.com/szabbenjamin/digionline/blob/master/force_epg_reload.sh

> Reboot után ismét üressé válik.
Elvileg ez üzemszerű, mert force módban van az EPG újratöltése.

Hagyd, hogy legenerálja, majd a config-ban állítsd a forceUpdate-ot false-ra. Ezutáni reboot esetén nem kéne gond legyen. Nem fogyott el a tárhely a gépen? Nem sérült meg az SD kártya?

**Comment by NH3CL** [comment]
ok, EPG megoldva köszi.

A lejátszás továbbra sem megy:

> 2021-07-20 14:42:18.886 T:1916318640  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/Minden csatorna/pvr.iptvsimple_1685233645.pvr
2021-07-20 14:42:18.896 T:1087357152  NOTICE: Creating InputStream
2021-07-20 14:42:18.899 T:1087357152   ERROR: CCurlFile::FillBuffer - Failed: Couldn't connect to server(7)
2021-07-20 14:42:18.900 T:1087357152   ERROR: CCurlFile::Open failed with code 0 for http://localhost:9999/channel/266.m3u8:
2021-07-20 14:42:18.901 T:1087357152  NOTICE: Creating Demuxer
2021-07-20 14:42:18.904 T:1087357152   ERROR: OpenDemuxStream - Error creating demuxer
2021-07-20 14:42:18.904 T:1087357152  NOTICE: CVideoPlayer::OnExit()
2021-07-20 14:42:19.759 T:1916318640  NOTICE: CVideoPlayer::CloseFile()
2021-07-20 14:42:19.760 T:1916318640  NOTICE: VideoPlayer: waiting for threads to exit
2021-07-20 14:42:19.760 T:1916318640  NOTICE: VideoPlayer: finished waiting
2021-07-20 14:42:19.775 T:1916318640  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/Minden csatorna/pvr.iptvsimple_1685233645.pvr
2021-07-20 14:42:19.779 T:1087357152  NOTICE: Creating InputStream
2021-07-20 14:42:19.785 T:1087357152   ERROR: CCurlFile::FillBuffer - Failed: Couldn't connect to server(7)
2021-07-20 14:42:19.787 T:1087357152   ERROR: CCurlFile::Open failed with code 0 for http://localhost:9999/channel/266.m3u8:
2021-07-20 14:42:19.788 T:1087357152  NOTICE: Creating Demuxer
2021-07-20 14:42:19.792 T:1087357152   ERROR: OpenDemuxStream - Error creating demuxer
2021-07-20 14:42:19.792 T:1087357152  NOTICE: CVideoPlayer::OnExit()
2021-07-20 14:42:19.809 T:1595900128   ERROR: EXCEPTION: XBMC is not playing any file
2021-07-20 14:42:19.810 T:1595900128   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: XBMC is not playing any file
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/service.autosubs/default.py", line 114, in onPlayBackStarted
                                                movieFullPath = xbmc.Player().getPlayingFile()
                                            RuntimeError: XBMC is not playing any file
                                            -->End of Python script error report<--
2021-07-20 14:42:20.376 T:1916318640  NOTICE: CVideoPlayer::CloseFile()
2021-07-20 14:42:20.376 T:1916318640  NOTICE: VideoPlayer: waiting for threads to exit
2021-07-20 14:42:20.376 T:1916318640  NOTICE: VideoPlayer: finished waiting
2021-07-20 14:42:20.409 T:1595900128   ERROR: EXCEPTION: XBMC is not playing any file
2021-07-20 14:42:20.410 T:1595900128   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: XBMC is not playing any file
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/service.autosubs/default.py", line 114, in onPlayBackStarted
                                                movieFullPath = xbmc.Player().getPlayingFile()
                                            RuntimeError: XBMC is not playing any file
                                            -->End of Python script error report<--

> root@NHTV:/home/osmc# service digionline status
* digionline.service - digionline servlet app
   Loaded: loaded (/etc/systemd/system/digionline.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2021-07-20 14:41:24 CEST; 35s ago
 Main PID: 670 (digionline.sh)
   Memory: 64.5M
   CGroup: /system.slice/digionline.service
           |-670 /bin/bash /home/osmc/digionline/digionline.sh
           |-671 npm
           |-689 sh -c node main.js
           `-690 node main.js

Jul 20 14:41:47 NHTV digionline.sh[670]: Tue Jul 20 2021 14:41:47 GMT+0200 (Central European Summer Time) [ '===Elerheto csatornalista formatumok kulso lejatszokhoz===' ]
Jul 20 14:41:47 NHTV digionline.sh[670]: Tue Jul 20 2021 14:41:47 GMT+0200 (Central European Summer Time) [ 'http://localhost:9999/channels_IPTV.m3u8' ]
Jul 20 14:41:47 NHTV digionline.sh[670]: Tue Jul 20 2021 14:41:47 GMT+0200 (Central European Summer Time) [ 'http://localhost:9999/channels_tvheadend.m3u8' ]
Jul 20 14:41:47 NHTV digionline.sh[670]: Tue Jul 20 2021 14:41:47 GMT+0200 (Central European Summer Time) [ 'http://localhost:9999/epg.xml' ]
Jul 20 14:41:47 NHTV digionline.sh[670]: Tue Jul 20 2021 14:41:47 GMT+0200 (Central European Summer Time) [ 'http://localhost:9999/channels.csv' ]
Jul 20 14:41:47 NHTV digionline.sh[670]: Tue Jul 20 2021 14:41:47 GMT+0200 (Central European Summer Time) [ 'Server is listening' ]
Jul 20 14:41:47 NHTV digionline.sh[670]: Tue Jul 20 2021 14:41:47 GMT+0200 (Central European Summer Time) [ 'Generating channel list...', '.m3u8' ]
Jul 20 14:41:47 NHTV digionline.sh[670]: Tue Jul 20 2021 14:41:47 GMT+0200 (Central European Summer Time) [ 'Channel list ready.' ]
Jul 20 14:41:47 NHTV digionline.sh[670]: Tue Jul 20 2021 14:41:47 GMT+0200 (Central European Summer Time) [ 'EPG lista t<C3><AD>pusa: heti' ]
Jul 20 14:41:47 NHTV digionline.sh[670]: Tue Jul 20 2021 14:41:47 GMT+0200 (Central European Summer Time) [ 'EPG naprakesz' ]

**Comment by szabbenjamin** [comment]
Egyelőre nem tudni mi van - ma reggel fedeztük fel, hogy a digionline rendszere megállt, a webes felületen már csak annyi látszik, hogy "nem található adat" - a hiba be lett jelentve, aztán majd kiderül, hogy átmeneti rendszerhiba-e, vagy ennyi volt... :/

**Comment by szabbenjamin** [comment]
A digionline rendszere elkezdett újra működni. @NH3CL légyszi futtass egy npm start-ot és másold be ide a tartalmát ha még mindig nem működik az app. Köszi!

**Comment by szabbenjamin** [comment]
A webes felület úgy tűnik visszatért. A probléma még fennáll nálad?

**Comment by NH3CL** [comment]
Megoldódott, lehet hogy a digi háza táján volt felfordulás, mert a probléma az országos leállás után jelentkezett (ami véletlen egybeesett a frissitéssel)
