### ISSUE TITLE
OSMC Raspberry pi4 hibák

### ISSUE THREAD

**Issue by NH3CL** [szabbenjamin/digionline#61]
Hello,

Pi4-re végre kijött az OSMC, viszont telepités után a digionline telepitő több helyen is véres marad.

Telepítés közben:

> ================================================================================
> ================================================================================
> 
>                               DEPRECATION WARNING
> 
>   Node.js 8.x LTS Carbon is no longer actively supported!
> 
>   You will not receive security or critical stability updates for this version.
> 
>   You should migrate to a supported version of Node.js as soon as possible.
>   Use the installation script that corresponds to the version of Node.js you
>   wish to install. e.g.
> 
>    * https://deb.nodesource.com/setup_12.x — Node.js 12 LTS "Erbium"
>    * https://deb.nodesource.com/setup_14.x — Node.js 14 LTS "Fermium" (recommended)
>    * https://deb.nodesource.com/setup_16.x — Node.js 16 "Gallium"
> 
>   Please see https://github.com/nodejs/Release for details about which
>   version may be appropriate for you.
> 
>   The NodeSource Node.js distributions repository contains
>   information both about supported versions of Node.js and supported Linux
>   distributions. To learn more about usage, see the repository:
>     https://github.com/nodesource/distributions
> 
> ================================================================================
> ================================================================================

Ehhez tartozik, hogy hiányzik továbbá egy `apt install npm` az installerből.

NPM install után (újrafuttatva a telepítőt) az alábbi logot írja ha futtatom a digionline.sh-t

> /home/osmc/digionline# ./digionline.sh
> npm WARN npm npm does not support Node.js v10.24.0
> npm WARN npm You should probably upgrade to a newer version of node as we
> npm WARN npm can't make any promises that npm will work with this version.
> npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
> npm WARN npm You can find the latest version at https://nodejs.org/
> 
> > digionline@2.2.6 start /home/osmc/digionline
> > node main.js
> 
> internal/modules/cjs/loader.js:638
>     throw err;
>     ^
> 
> Error: Cannot find module '/home/osmc/digionline/main.js'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! digionline@2.2.6 start: `node main.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the digionline@2.2.6 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:

> /home/osmc/digionline# cat /root/.npm/_logs/2021-09-06T14_08_35_427Z-debug.log
> 0 info it worked if it ends with ok
> 1 warn npm npm does not support Node.js v10.24.0
> 2 warn npm You should probably upgrade to a newer version of node as we
> 3 warn npm can't make any promises that npm will work with this version.
> 4 warn npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
> 5 warn npm You can find the latest version at https://nodejs.org/
> 6 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
> 7 info using npm@5.8.0
> 8 info using node@v10.24.0
> 9 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 10 info lifecycle digionline@2.2.6~prestart: digionline@2.2.6
> 11 info lifecycle digionline@2.2.6~start: digionline@2.2.6
> 12 verbose lifecycle digionline@2.2.6~start: unsafe-perm in lifecycle true
> 13 verbose lifecycle digionline@2.2.6~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/osmc/digionline/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> 14 verbose lifecycle digionline@2.2.6~start: CWD: /home/osmc/digionline
> 15 silly lifecycle digionline@2.2.6~start: Args: [ '-c', 'node main.js' ]
> 16 silly lifecycle digionline@2.2.6~start: Returned: code: 1  signal: null
> 17 info lifecycle digionline@2.2.6~start: Failed to exec start script
> 18 verbose stack Error: digionline@2.2.6 start: `node main.js`
> 18 verbose stack Exit status 1
> 18 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:283:16)
> 18 verbose stack     at EventEmitter.emit (events.js:198:13)
> 18 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 18 verbose stack     at ChildProcess.emit (events.js:198:13)
> 18 verbose stack     at maybeClose (internal/child_process.js:982:16)
> 18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> 19 verbose pkgid digionline@2.2.6
> 20 verbose cwd /home/osmc/digionline
> 21 verbose Linux 5.10.32-1-osmc
> 22 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
> 23 verbose node v10.24.0
> 24 verbose npm  v5.8.0
> 25 error code ELIFECYCLE
> 26 error errno 1
> 27 error digionline@2.2.6 start: `node main.js`
> 27 error Exit status 1
> 28 error Failed at the digionline@2.2.6 start script.
> 28 error This is probably not a problem with npm. There is likely additional logging output above.
> 29 verbose exit [ 1, true ]

**Comment by szabbenjamin** [comment]
Köszi a jelzést, ahogy figyelem még igencsak instabil a kiadott OSMC, de már használható és miután összeszedte magát meglepően gyors is a csatornaváltás. A telepítő release-ként lett kiadva:
[https://github.com/szabbenjamin/digionline/releases/tag/v2.2.9](https://github.com/szabbenjamin/digionline/releases/tag/v2.2.9)

Ha problémád akad a használatával jelezz vissza!

**Comment by NH3CL** [comment]
Tényleg gyorsabb, bár az szerintem inkább csak a hardvernak tudható be (nekem 4 GB-s modell van). Köszönöm a gyors fixet, hiba esetén jelentkezem!
