### ISSUE TITLE
Ugráló videó folyam

### ISSUE THREAD

**Issue by cuh7b5** [szabbenjamin/digionline#64]
Többször tapasztaltam már, most épp az Izaura TV-nél találkozom az alábbi jelenséggel:

HQ minőségben elindul a stream, egy ideig szépen működik. Majd néhány perc múlva akadozni kezd, és pár tizedmásodpercre/másodpercre belerak kb. egy perccel korábbi részleteket. Majd felgyorsul, utoléri magát, és ismét előfordul ugyanez. Elég zavaró, lényegében élvezhetetlen így az adás.

A szolgáltató webes lejátszója nem csinálja ezt, ott rendben megy a stream.

A logban semmi hiba nem látszik.

Nálam reprodukálható. Bármikor elindítom az Izaura TV-t, a service-en keresztül néhány perc elteltével jelentkezik. A digi web felületén soha nem csinálja ezt. Tény, hogy a digi streamjei sem túl minőségiek, de ez mintha nem tőlük eredne.

Core i5-ös 16G RAM-os laptopon történik mindez, Arch Linux alatt. Az internet sávszélesség és minőség rendben van.

Egyébként köszi a sok fáradozást ezzel a projekttel!

**Comment by szabbenjamin** [comment]
Hali!
Csak ez az egy csatorna problémás, vagy az összes többinél is ez a hibajelenség történik?
Van változás akkor ha átállítod a stream minőségét a config fájlban?

**Comment by cuh7b5** [comment]
Úgy tűnik, csak az Izaura csatornánál van ez a probléma és csak HQ minőségben. MQ esetén már nem észlelem ezt.

**Comment by szabbenjamin** [comment]
Megnézem nálam is mi a helyzet, de valószínű, hogy a digi által küldött stream-el nem stimmel valami, amit nálad (feltételezem a Kodi) nem tud lekezelni. Ilyen problémát akkor láttam még régebben amikor VLC-n nyitottam meg egyes stream-eket. VLC-n ugrált a kép, Kodi-n rendben volt.

Felírom magamnak egy következő feature-be, hogy lehetőség legyen a csatornák minőségének egyenként való beállítása is.

**Comment by cuh7b5** [comment]
Most rendben van, HQ-ban is rendben működik. Valami stream-specifikus probléma lehetett. Érdekes, hogy egyszercsak elmúlt.
