### ISSUE TITLE
Node verzió

### ISSUE THREAD

**Issue by angyalz** [szabbenjamin/digionline#65]
Nem túl barátságos lépés, hogy az installer a rendszeren már meglévő node.js 16 repoját átírja a node.js 8-ra

**Comment by szabbenjamin** [comment]
Hali!
A 8-as node az a verzió ami minden raspi-n képes - tudomásom szerint - még elfutni. Ha már egy meglévő rendszerre rakod akkor ne az installert használd, hanem használj dockert, vagy telepítsd lépésről lépésre a saját rendszerednek megfelelően.
