### ISSUE TITLE
Digi logout után nem indul a stream

### ISSUE THREAD

**Issue by cuh7b5** [szabbenjamin/digionline#66]
Régóta tapasztalható jelenség, hogy ha egy ideig nem használom a szolgáltatást, majd megpróbálok elindítani egy TV csatornát, akkor nem indul el a stream. A Kodi ilyenkor 30 másodpercet vár, addig semmit nem lehet csinálni, ezért elég zavaró a jelenség. Más lejátszóval (smplayer) sem indul el. Ez után ismét elindítom a csatornát, és a stream szépen megy. Utána már nincs ilyen jelenség, amíg aktívan használom a csatornákat. Majd legközelebb (pl. következő nap) ismét ugyanez történik.

Amikor nem indul a stream, akkor ez látszik a logban:

```
Thu Jan 20 2022 12:31:32 GMT+0100 (Central European Standard Time) [ 'GET channel 284' ]
Thu Jan 20 2022 12:31:33 GMT+0100 (Central European Standard Time) [ 'Unexpected response! Are we logged in?' ]
Thu Jan 20 2022 12:31:33 GMT+0100 (Central European Standard Time) [ 'loaded from request', 'id_284' ]
Thu Jan 20 2022 12:31:33 GMT+0100 (Central European Standard Time) [ { error: true, message: 'Kérjük jelentkezzen be újra!' } ]
Thu Jan 20 2022 12:31:33 GMT+0100 (Central European Standard Time) [ 'Login digionline.hu' ]
Thu Jan 20 2022 12:31:33 GMT+0100 (Central European Standard Time) [
  'Hello packet sent...',
  '{"error":true,"message":"K\\u00e9rj\\u00fck jelentkezzen be \\u00fajra!"}'
]
Thu Jan 20 2022 12:31:35 GMT+0100 (Central European Standard Time) [ 'Logged in: xxxxxxxx@gmail.com' ]
@
@
@
@
@ Ha támogatni szeretnéd a munkámat (vagy meg szeretnél hívni egy sörre, kávéra) Paypal-on van erre lehetőséged: https://paypal.me/dicsportal
@
@
@
Thu Jan 20 2022 12:31:35 GMT+0100 (Central European Standard Time) [ 'Logged in' ]

```

Gondolom, az történik, hogy indítanám a stream-et, de a digi időközben kidobott, így a servlet újra bejelentkezik. Az elindított stream viszont nem indul el a 'Logged in' üzenet után sem, újra el kell indítani, hogy működjön.

Van esetleg arra megoldás, hogy az újraazonosítás után automatikusan működjön az elindított a stream?

Workaround-ként egy cron jobba beraktam, hogy 50 percenként induljon újra a servlet (feltéve ha a kodin épp nincs lejátszás, hogy ne lőjön ki egy épp futó streamet). Ez kikényszeríti az újraazonosítást. Nem tudom, mi a digi automatikus kiléptetési ideje, ezért 1 óránál kisebb értéket adtam meg.

**Comment by szabbenjamin** [comment]
Érdekes hibajelenség, köszi a visszajelzést, a napokban ránézek!

**Comment by cuh7b5** [comment]
Köszi! Egyébként tesztelési céllal a jelenséget úgy lehet kikényszeríteni, hogy egy böngészőben megnyitsz 2-3 digionline.hu ablakot, mindben elindítasz más-más tv adásokat. Ilyenkor a többi csatlakozott helyről kiléptet. Ekkor Kodi alatt elindítasz egy TV csatornát és ilyenkor nem indul el elsőre, a jelzett naplóüzenet keletkezik. ...legalábbis nálam. :)

**Comment by NH3CL** [comment]
+1, ez nálam is jelentkezik rpi 4-en, minden reggel.

**Comment by szabbenjamin** [comment]
Hogy ne érjen véget a munkamenet egy próbával a hiba javításra került, légyszi update-eljetek, teszteljétek le és jelezzetek vissza!
https://github.com/szabbenjamin/digionline/commit/f013b40f7728a509ae2beb6e251d72eb82f0a28a

**Comment by cuh7b5** [comment]
Működik! Nagyon köszi!
