### ISSUE TITLE
Nem rendelkezik előfizetéssel az adás megtekintésére. támogatása

### ISSUE THREAD

**Issue by gmeszaros** [szabbenjamin/digionline#67]
Hello,

nagyon tetszik a program, most kezdtem el tvheadend-del használni.
Miközben a TVH scan-neli a csatornákat az alkalmazás leáll amikor a 258-as FilmNow-hoz ér, mert nincs rá előfizetésem.
Bele lehetne esetleg tenni a programba, hogy ilyenkor ezeket a csatornákat átugorja vagy elrejtse?

Köszönöm.

**Comment by szabbenjamin** [comment]
Hali!
Ahogy figyelem sajnos csak akkor derül ki, hogy nincs jogosultság a csatorna megnyitására amikor már épp megnyitnád - mivel kialakulhat olyan eset, hogy egy-egy csatorna csak ideiglenesen nem elérhető így a listából én nem venném ezeket ki.

A problémát úgy orvosolhatod ha a tvheadend alatt a Configuration -> DVB Inputs -> Muxes alatt a hibás csatornát eltávolítod.
