### ISSUE TITLE
EPG xml időzítés kezelése

### ISSUE THREAD

**Issue by Sentinel800** [szabbenjamin/digionline#7]
Az EPG legenerálódik és használják a csatornák, de a KODI simple iptv plugin EPG része nem tudja jól csúsztatni. Nyilván ez a hiba nem feltétlen az xml generálás hibája, maga a kiegészítő nem biztos, hogy jól kezeli az xml-t. Emiatt akkor működhet jól, ha kulcsrakészen, jó időzítéssel generálódik le. 

Ehhez a config.js ben állítható paraméterként valahogy csúsztatni kéne a generált xml ben lévő időzítéseket órában (percre nincs szükség) + - irányban vagy külsőleg, kód által, generálás előtt vagy xmltv paraméterek segítségével (ha van ilyen paramétere).

**Comment by cr04ch** [comment]
Valószínűleg a generálással sincs minden rendben, nekem legalábbis furcsa, hogy az M3U fájlokban a `tvg-shift` értéke 3, az XML-ben pedig az időeltolás +0100, holott jelenleg 2 órás eltolásra lenne szükség. Ezekkel az értékekkel nálam a műsorokat két órával jelzi korábbra (az IPTV Simple Client-ben nincs beállítva eltolás).

A mellékelt módosítások után generált M3U és XML fájlokban mindenhol 2 órás eltolás szerepel, és így nálam jól jelzi ki az időpontokat. A servletet futtató gép és a Kodi időzónája is Europe/Budapest.

[tz_offset.diff.gz](https://github.com/szabbenjamin/digionline/files/2224349/tz_offset.diff.gz)

**Comment by szabbenjamin** [comment]
@cr04ch, küldd be a módosításodat és lecsekkoljuk! 👍

**Comment by szabbenjamin** [comment]
Kipróbáltam külső pluginnal (xmltv), pontosan ugyanazokat a hibákat produkálja - ez valszeg az IPTV plugin hibája lesz.
Ajánlom a tvheadend használatát. Kicsit bonyolultabb a felkonfigurálása, de stabil az EPG kezelése.
https://github.com/mattiash/xmltv/blob/master/grab/huro/tv_grab_huro.in

A jövőben készíteni fogok tvheadend beállítási tutorialt is ha van rá igény.
