### ISSUE TITLE
Viasat2 és The Fishing&Hunting EPG hiány

### ISSUE THREAD

**Issue by Terenyeitamas** [szabbenjamin/digionline#70]
Szia!

A Viasat2 és a The Fishing&Hunting csatornákon nincs EPG. A Viasat2-nél valószínű a névváltozás miatt, mert az előtte Sony Max volt.

Egyébként a csatornák gond nélkül nézhetők, csak az EPG hiányzik.

Köszi, ha ránézel:
Tamás

**Comment by NH3CL** [comment]
+1

**Comment by szabbenjamin** [comment]
Javítva.
https://github.com/szabbenjamin/digionline/releases/tag/V2.2.11
