### ISSUE TITLE
Hiányzó műsorújság

### ISSUE THREAD

**Issue by NH3CL** [szabbenjamin/digionline#75]
Sziasztok,

Először is ezer hála és köszönet a pluginért!

Hiányzik a műsorújság az alábbi csatornáknál:
Animal Planet
Filmbox Extra
ID

**Comment by Terenyeitamas** [comment]
Szia!

Húzd le a legutóbbi változást, benne van epg_channel_urls.json fájlban a jelzett 3 csatorna. 
Most teszteltem (2023.01.25. 13:10-kor) az epg.xml újratöltését, majd Kodi v20-ban ellenőriztem az EPG-t, és ott van mindhárom csatorna műsora.

Üdv:
Tamás

**Comment by NH3CL** [comment]
It works, close.
