### ISSUE TITLE
m3u8 nem jön létre

### ISSUE THREAD

**Issue by petrovicscsaba** [szabbenjamin/digionline#77]
Raspberry Pi 3- ra felraktam OSMC 20230124 verzót, utána egyből megcsináltam github leírás alapján SSH-n a feltöltést, telepítés közben megadtam Digionline email címem és jelszavam.
Telepítés lezárult, Pi újra indult, Digionline mappa létrejött, de epg.xml fájl üres és m3u8 fájl nem található.
Többszöri telepítés és újraindítás után a képernyő bal felső sarkában hibaüzenet, hogy a servlet nem tudott elindulni.

**Comment by petrovicscsaba** [comment]
Kipróbáltam régebbi OSMC verziókon is pl. 20191107 Kodi 18.4 is hátha sikerül, de ugyan az a probléma, a servlet nem indul.
wget -N https://raw.githubusercontent.com/szabbenjamin/digionline/master/osmc_installer.sh && bash osmc_installer.sh
parancsot ssh-n keresztül elindítom, kitöltöm digi-s emailt és jelszót, a Digionline mappa létrejön de epg.xml fájl üres és m3u8 fájl továbbra sincs.
Lehet itt egyáltalán segítséget kapni vagy már RPI 3 nincsen?

**Comment by droM4X** [comment]
Ha a log fájlt bedobod ide, talán tudunk rá mondani valamit, így látatlanban nehéz lesz. Ha nem hoz létre fájlt, lehet pl. azért is mert nincs írásjoga.

Ha tudsz dockert használni, akkor inkább azt a verziót próbáld, ott nincsenek ilyen problémák és a rendszerbe se épül be. Itt van pl. az én forkom: https://github.com/droM4X/digionline
Még benne van az osmc telepítő is, de ki fogom venni, és csak docker only lesz, amint lesz rá időm.

**Comment by petrovicscsaba** [comment]
Kedves Gábor!
Eddig még nem használtam dockert és leírások alapján feltettem dockert és Portainer-en belül Stack-ban és Containers-ben is beállítottam a fork leírásnak megfelelően.
Nem volt egyszerű, még nem használtam, de most tökéletesen működik 51 tévécsatorna, többszöri újraindítás után is hamar létrejön a műsorújság, minden szépen működik.
Köszönöm szépen a segítséget és javaslatot és a fork fejlesztést is! :-)

**Comment by droM4X** [comment]
Nincs mit, használd egészséggel.
